# Final lightcurve feature list for LAISS
lc_features_const = [
    "feature_amplitude_magn_r",
    "feature_anderson_darling_normal_magn_r",
    "feature_beyond_2_std_magn_r",
    "feature_cusum_magn_r",
    "feature_kurtosis_magn_r",
    "feature_median_absolute_deviation_magn_r",
    "feature_skew_magn_r",
    "feature_standard_deviation_magn_r",
    "feature_weighted_mean_magn_r",
    "feature_amplitude_magn_g",
    "feature_anderson_darling_normal_magn_g",
    "feature_beyond_2_std_magn_g",
    "feature_cusum_magn_g",
    "feature_kurtosis_magn_g",
    "feature_median_absolute_deviation_magn_g",
    "feature_skew_magn_g",
    "feature_standard_deviation_magn_g",
    "feature_weighted_mean_magn_g",
]


# Final host feature list for LAISS
host_features_const = [
    "gKronMagCorrected",
    "gKronRad",
    "gExtNSigma",
    "rKronMagCorrected",
    "rKronRad",
    "rExtNSigma",
    "iKronMagCorrected",
    "iKronRad",
    "iExtNSigma",
    "zKronMagCorrected",
    "zKronRad",
    "zExtNSigma",
    "gminusrKronMag",
    "rminusiKronMag",
    "iminuszKronMag",
]

# All features from dataset bank needed to engineer host features
raw_host_features_const = [
    "gmomentXX",
    "gmomentYY",
    "gmomentXY",
    "gKronMag",
    "gKronMagErr",
    "gKronRad",
    "gExtNSigma",
    "rmomentXX",
    "rmomentYY",
    "rmomentXY",
    "rKronMag",
    "rKronMagErr",
    "rKronRad",
    "rExtNSigma",
    "imomentXX",
    "imomentYY",
    "imomentXY",
    "iKronMag",
    "iKronMagErr",
    "iKronRad",
    "iExtNSigma",
    "zmomentXX",
    "zmomentYY",
    "zmomentXY",
    "zKronMag",
    "zKronMagErr",
    "zKronRad",
    "zExtNSigma",
]


# Original LAISS features for testing
# lc_features_const = [
#     "feature_amplitude_magn_r",
#     "feature_anderson_darling_normal_magn_r",
#     "feature_beyond_1_std_magn_r",
#     "feature_beyond_2_std_magn_r",
#     "feature_cusum_magn_r",
#     "feature_inter_percentile_range_2_magn_r",
#     "feature_inter_percentile_range_10_magn_r",
#     "feature_inter_percentile_range_25_magn_r",
#     "feature_kurtosis_magn_r",
#     "feature_linear_fit_slope_magn_r",
#     "feature_linear_fit_slope_sigma_magn_r",
#     "feature_magnitude_percentage_ratio_40_5_magn_r",
#     "feature_magnitude_percentage_ratio_20_5_magn_r",
#     "feature_mean_magn_r",
#     "feature_median_absolute_deviation_magn_r",
#     "feature_percent_amplitude_magn_r",
#     "feature_median_buffer_range_percentage_10_magn_r",
#     "feature_median_buffer_range_percentage_20_magn_r",
#     "feature_percent_difference_magnitude_percentile_5_magn_r",
#     "feature_percent_difference_magnitude_percentile_10_magn_r",
#     "feature_skew_magn_r",
#     "feature_standard_deviation_magn_r",
#     "feature_stetson_k_magn_r",
#     "feature_weighted_mean_magn_r",
#     "feature_anderson_darling_normal_flux_r",
#     "feature_cusum_flux_r",
#     "feature_excess_variance_flux_r",
#     "feature_kurtosis_flux_r",
#     "feature_mean_variance_flux_r",
#     "feature_skew_flux_r",
#     "feature_stetson_k_flux_r",
#     "feature_amplitude_magn_g",
#     "feature_anderson_darling_normal_magn_g",
#     "feature_beyond_1_std_magn_g",
#     "feature_beyond_2_std_magn_g",
#     "feature_cusum_magn_g",
#     "feature_inter_percentile_range_2_magn_g",
#     "feature_inter_percentile_range_10_magn_g",
#     "feature_inter_percentile_range_25_magn_g",
#     "feature_kurtosis_magn_g",
#     "feature_linear_fit_slope_magn_g",
#     "feature_linear_fit_slope_sigma_magn_g",
#     "feature_magnitude_percentage_ratio_40_5_magn_g",
#     "feature_magnitude_percentage_ratio_20_5_magn_g",
#     "feature_mean_magn_g",
#     "feature_median_absolute_deviation_magn_g",
#     "feature_median_buffer_range_percentage_10_magn_g",
#     "feature_median_buffer_range_percentage_20_magn_g",
#     "feature_percent_amplitude_magn_g",
#     "feature_percent_difference_magnitude_percentile_5_magn_g",
#     "feature_percent_difference_magnitude_percentile_10_magn_g",
#     "feature_skew_magn_g",
#     "feature_standard_deviation_magn_g",
#     "feature_stetson_k_magn_g",
#     "feature_weighted_mean_magn_g",
#     "feature_anderson_darling_normal_flux_g",
#     "feature_cusum_flux_g",
#     "feature_excess_variance_flux_g",
#     "feature_kurtosis_flux_g",
#     "feature_mean_variance_flux_g",
#     "feature_skew_flux_g",
#     "feature_stetson_k_flux_g",
# ]


# raw_host_features_const = [
#     "gmomentXX",
#     "gmomentXY",
#     "gmomentYY",
#     "gmomentR1",
#     "gmomentRH",
#     "gPSFFlux",
#     "gApFlux",
#     "gKronFlux",
#     "gKronRad",
#     "gExtNSigma",
#     "rmomentXX",
#     "rmomentXY",
#     "rmomentYY",
#     "rmomentR1",
#     "rmomentRH",
#     "rPSFFlux",
#     "rApFlux",
#     "rKronFlux",
#     "rKronRad",
#     "rExtNSigma",
#     "imomentXX",
#     "imomentXY",
#     "imomentYY",
#     "imomentR1",
#     "imomentRH",
#     "iPSFFlux",
#     "iApFlux",
#     "iKronFlux",
#     "iKronRad",
#     "iExtNSigma",
#     "zmomentXX",
#     "zmomentXY",
#     "zmomentYY",
#     "zmomentR1",
#     "zmomentRH",
#     "zPSFFlux",
#     "zApFlux",
#     "zKronFlux",
#     "zKronRad",
#     "zExtNSigma",
#     "ymomentXX",
#     "ymomentXY",
#     "ymomentYY",
#     "ymomentR1",
#     "ymomentRH",
#     "yPSFFlux",
#     "yApFlux",
#     "yKronFlux",
#     "yKronRad",
#     "yExtNSigma",
#     "i-z",
#     "gApMag_gKronMag",
#     "rApMag_rKronMag",
#     "iApMag_iKronMag",
#     "zApMag_zKronMag",
#     "yApMag_yKronMag",
#     "7DCD",
#     "dist/DLR",
# ] + [
#     "gKronMag",
#     "gKronMagErr",
#     "rKronMag",
#     "rKronMagErr",
#     "iKronMag",
#     "iKronMagErr",
#     "zKronMag",
#     "zKronMagErr",
# ]

# host_features_const = [
#     "gmomentXX",
#     "gmomentXY",
#     "gmomentYY",
#     "gmomentR1",
#     "gmomentRH",
#     "gPSFFlux",
#     "gApFlux",
#     "gKronFlux",
#     "gKronRad",
#     "gExtNSigma",
#     "rmomentXX",
#     "rmomentXY",
#     "rmomentYY",
#     "rmomentR1",
#     "rmomentRH",
#     "rPSFFlux",
#     "rApFlux",
#     "rKronFlux",
#     "rKronRad",
#     "rExtNSigma",
#     "imomentXX",
#     "imomentXY",
#     "imomentYY",
#     "imomentR1",
#     "imomentRH",
#     "iPSFFlux",
#     "iApFlux",
#     "iKronFlux",
#     "iKronRad",
#     "iExtNSigma",
#     "zmomentXX",
#     "zmomentXY",
#     "zmomentYY",
#     "zmomentR1",
#     "zmomentRH",
#     "zPSFFlux",
#     "zApFlux",
#     "zKronFlux",
#     "zKronRad",
#     "zExtNSigma",
#     "ymomentXX",
#     "ymomentXY",
#     "ymomentYY",
#     "ymomentR1",
#     "ymomentRH",
#     "yPSFFlux",
#     "yApFlux",
#     "yKronFlux",
#     "yKronRad",
#     "yExtNSigma",
#     "i-z",
#     "gApMag_gKronMag",
#     "rApMag_rKronMag",
#     "iApMag_iKronMag",
#     "zApMag_zKronMag",
#     "yApMag_yKronMag",
#     "7DCD",
#     "dist/DLR",
# ]
